runtime: nodejs16 # or another supported version

instance_class: B1

manual_scaling:
  instances: 2

env_variables:
  PORT: 8080

handlers:
- url: /public/stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto